
<br>
<center><img src="https://i.imgur.com/hkb7Bq7.png" width="500"></center>


### Prof. José Manuel Magallanes, PhD

* Full Professor, Departamento de Ciencias Sociales, Pontificia Universidad Católica del Perú, [jmagallanes@pucp.edu.pe](mailto:jmagallanes@pucp.edu.pe)

* Visiting Professor, Evans School of Public Policy and Governance / Senior Data Science Fellow, eScience Institute, University of Washington
_____

Preparation

In [ ]:
!python -V

Python 3.10.12


In [ ]:
%load_ext rpy2.ipython
# you need this to make R work in this notebook

## 1. Creating



In [ ]:
### The Python List:
aList_P=["Qing", "Françoise", "Raúl", "Bjork","Marie","Jim","Tere"]

### The Python Tuple:
aTuple_P=("China", "Senegal", "España", "Norway","Korea","USA","Bolivia")

### The Python Set:
aSet_P={"Bachelor", "Master","Master","Master", "PhD","Bachelor","Bachelor"}

### The Python Vector:

import numpy as np

aVector_P=np.array([32,33,28,30,29,33,34,27])

In [ ]:
# checking data types
type(aList_P), type(aSet_P), type(aTuple_P), type(aVector_P)

(list, set, tuple, numpy.ndarray)

In [ ]:
# checking contents
aVector_P

array([32, 33, 28, 30, 29, 33, 34, 27])

In [ ]:
# checking contents
aSet_P

{'Bachelor', 'Master', 'PhD'}

In [ ]:
%%R # you need this to run R code in a cell

### The R List:
aList_R=list("Qing", "Françoise", "Raúl", "Bjork","Marie","Jim","Tere","Tina")

### The R Vector:
aVector_R=c(32,33,28,30,29,33,34,27)

In [ ]:
%%R
# checking data types
typeof(aList_R)

[1] "list"


In [ ]:
%%R
# checking data types
typeof(aVector_R)

[1] "double"


In [ ]:
%%R
# checking contents
aVector_R

[1] 32 33 28 30 29 33 34 27


## 2. Accessing

In [ ]:
# Positions in Python start at: 0.

aList_P[0] # see first element in a list

'Qing'

In [ ]:
aVector_P[-1] # the last element

27

In [ ]:
type(aList_P[0]) # see the type of the first element

str

In [ ]:
%%R
# Positions in R start at: 1.
aList_R[[1]]  # see first element in a list

[1] "Qing"


In [ ]:
%%R
tail(aVector_R,1) # see last element in a vector

[1] 27


In [ ]:
# this will not work
# aSet_P[0]

In [ ]:
aTuple_P[2]

'España'

## 3. Modifying

Tuples can not be modified.



### Replacing


#### by Position

Indexing does not work with SETS so replace by position will not work

In [ ]:
aList_P=["Qing", "Françoise", "Raúl", "Bjork","Marie","Jim","Tere"]
aList_P[1]="Francisca"

# changes:
aList_P

['Qing', 'Francisca', 'Raúl', 'Bjork', 'Marie', 'Jim', 'Tere']

In [ ]:
aVector_P=np.array([32,33,28,30,29,33,34,27])
aVector_P[2]=58

# changes:
aVector_P

array([32, 33, 58, 30, 29, 33, 34, 27])

In [ ]:
%%R
aList_R=list("Qing", "Françoise", "Raúl", "Bjork","Marie","Jim","Tere")
aList_R[2]="Francisca"

# changes:
aList_R

[[1]]
[1] "Qing"

[[2]]
[1] "Francisca"

[[3]]
[1] "Raúl"

[[4]]
[1] "Bjork"

[[5]]
[1] "Marie"

[[6]]
[1] "Jim"

[[7]]
[1] "Tere"



In [ ]:
%%R

aVector_R=c(32,33,28,30,29,33,34,27)
aVector_R[3]=58

# changes:
aVector_R

[1] 32 33 58 30 29 33 34 27



#### By Value

Item assigment does not work with SETS so replace by value will not work.

In [ ]:
aList_P=["Mary" if val == "Marie" else val for val in aList_P]
#changes
aList_P

['Qing', 'Francisca', 'Raúl', 'Bjork', 'Mary', 'Jim', 'Tere']

In [ ]:
aVector_P[aVector_P==27]= 72

#changes
aVector_P

array([32, 33, 58, 30, 29, 33, 34, 72])

In [ ]:
%%R

aList_R[aList_R=='Marie']="Mary"

#changes
aList_R

[[1]]
[1] "Qing"

[[2]]
[1] "Francisca"

[[3]]
[1] "Raúl"

[[4]]
[1] "Bjork"

[[5]]
[1] "Mary"

[[6]]
[1] "Jim"

[[7]]
[1] "Tere"



In [ ]:
%%R

aVector_R[aVector_R==27]= 72

# changes
aVector_R

[1] 32 33 58 30 29 33 34 72


### Deleting

You can not delete elements in a *tuple*.

#### By Position

You can not delete by position in Python SETs

In [ ]:
# using 'del' in lists:
newList_P=[1,2,3,'a']

#last value, but you can write several indexes as slice
del newList_P[0:2]

# changes
newList_P

[3, 'a']

In [ ]:
# Using 'pop' in lists you get the last value:

newList_P=[1,2,3,'a']
newList_P.pop()

'a'

In [ ]:
# and shrink the list
newList_P

[1, 2, 3]

In [ ]:
newVector_P=np.array([1,2,3,'a'])

#first value, but you can write several indexes in a list
newVector_P=np.delete(newVector_P,[-1,-2])

newVector_P


array(['1', '2'], dtype='<U21')

In [ ]:
newSet_P={1,2,3,'a'}

In [ ]:
%%R

newList_R=list(1,2,3,'a')

# just use the 'minus' sign
newList_R=newList_R[-c(1:2)]

#changes
newList_R

[[1]]
[1] 3

[[2]]
[1] "a"



In [ ]:
%%R

newVector_R=c(1,2,3,'a')
newVector_R=newVector_R[-c(3,4)]

#changes
newVector_R

[1] "1" "2"


**NOTE:**  _**del**_ will delete the list if no index is given.

#### by Value

In [ ]:
# remove for list
newList_P=[1,2,3,'a','a',22]
newList_P.remove('a')
newList_P

[1, 2, 3, 'a', 22]

In [ ]:
# remove for list
newList_P=[1,2,3,'a','a',22]
newList_P.remove('A')
newList_P

ValueError: ignored

In [ ]:
# deleting every  value:

newList_P=[1,2,3,'a','a',22]
newList_P=[values for values in newList_P if values !='a']

# you get:
newList_P

[1, 2, 3, 22]

In [ ]:
newSet_P={1,2,3,'a','a',22}

newSet_P.remove('a')
newSet_P

{1, 2, 3, 22}

In [ ]:
newSet_P={1,2,3,'a','a',22}

newSet_P.discard('A')
newSet_P

{1, 2, 22, 3, 'a'}

In [ ]:
newVector_P=np.array([1,2,3,'a','a',22])
newVector_P=np.delete(newVector_P, np.where(newVector_P == 'a'))

# changes
newVector_P

array(['1', '2', '3', '22'], dtype='<U21')

In [ ]:
newVector_P=np.array([1,2,3,'a','a',22])
newVector_P=newVector_P[newVector_P!='a']

# changes
newVector_P

array(['1', '2', '3', '22'], dtype='<U21')

In [ ]:
%%R

newList_R=list(1,2,3,'a','a',22)
newList_R=newList_R[newList_R !='a']

newList_R


[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 22



In [ ]:
%%R

newVector_R=c(1,2,3,'a','a',22)
newVector_R=newVector_R[newVector_R !='a']

newVector_R


[1] "1"  "2"  "3"  "22"


### Inserting values

In [ ]:
# at the end
listP=[1,'a']
listP.append("cde")
listP

[1, 'a', 'cde']

In [ ]:
# specific position
listP=[1,'a']
listP.insert(1,"cde")
listP

[1, 'cde', 'a']

In [ ]:
%%R

# at the end
listR=list(1,'a')
listR=append(listR,'cde')
listR

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] "cde"



In [ ]:
%%R

# specific position
listR=list(1,'a')
listR=append(listR,'cde',after=1)
listR

[[1]]
[1] 1

[[2]]
[1] "cde"

[[3]]
[1] "a"



In [ ]:
# in a set
cSet={'a','b','cc'}
cSet.update(('dd',))

# changes
cSet

{'a', 'b', 'cc', 'dd'}

In [ ]:
# in a vector at the end
vectorP=np.array([1,2,3,4])
vectorP=np.append(vectorP,5)

# changes
vectorP

array([1, 2, 3, 4, 5])

In [ ]:
# in a vector at a specific position
vectorP=np.array([1,2,3,4])
vectorP=np.insert(vectorP,obj=1,values=10) #obj is position
vectorP

array([ 1, 10,  2,  3,  4])

In [ ]:
%%R

# in a vector at the end
vectorR=c(1,2,3,4)
vectorR=c(vectorR,5)
vectorR

[1] 1 2 3 4 5


In [ ]:
%%R

# in a vector at a specific position
vectorR=c(1,2,3,4)
vectorR=append(vectorR,10,after=1)
vectorR

[1]  1 10  2  3  4


## Concatenating

In [ ]:
listA_P=[1,2,3]
listB_P=['a', 'b', 'c']
listC=listA_P + listB_P

# a new list
listC

[1, 2, 3, 'a', 'b', 'c']

In [ ]:
listA_P.extend(listB_P)

# an old list extended
listA_P

[1, 2, 3, 'a', 'b', 'c']

In [ ]:
#notice
listA1_P=[1,2,3]
listB1_P=['a', 'b', 'c']
listA1_P.append(listB1_P)
listA1_P

[1, 2, 3, ['a', 'b', 'c']]

In [ ]:
%%R

listA_R=list(1,2,3)
listB_R=list('a', 'b', 'c')
listC_R=append(listA_R, listB_R)
# new list
listC_R

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "a"

[[5]]
[1] "b"

[[6]]
[1] "c"



In [ ]:
%%R

listC_R[[4]]

[1] "a"


In [ ]:
%%R
listC_R=append(listA_R, list(listB_R))
listC_R

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[[4]][[1]]
[1] "a"

[[4]][[2]]
[1] "b"

[[4]][[3]]
[1] "c"




In [ ]:
%%R
listC_R[[4]]

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"



In [ ]:
vectorP1=np.array([1,2,3,4])
vectorP2=np.array(['a','b'])
vectorP12=np.concatenate((vectorP1,vectorP2))

# new vector
vectorP12

array(['1', '2', '3', '4', 'a', 'b'], dtype='<U21')

In [ ]:
%%R
vectorR1=c(1,2,3,4)
vectorR2=c('a','b')
vectorR12=c(vectorR1,vectorR2)
# new vector
vectorR12

[1] "1" "2" "3" "4" "a" "b"


In [ ]:
# in sets we talk about union
set1={'a','b','c','d'}
set2={1,2,3,4}
set3={'a',2,3,'d'}

set4=set1|set2|set3
#new set
set4

{1, 2, 3, 4, 'a', 'b', 'c', 'd'}

In [ ]:
# you can concatenate tuples, but into a new one

tuple1=('a','b','c','d')
tuple2=(1,2,3,4)
tuple3=('a',2,3,'d')
tuple4=tuple1+tuple2+tuple3

#new tuple
tuple4

('a', 'b', 'c', 'd', 1, 2, 3, 4, 'a', 2, 3, 'd')